#!/bin/bash
VPNPATH="/etc/openvpn/nord/ovpn_tcp/"
cd $VPNPATH
if [ $# -eq 1 ];
then
    VPNPATH="$VPNPATH$1.nordvpn.com.tcp.ovpn"
    if [ -f $VPNPATH ];
    then
        openvpn "$VPNPATH" &
    else
        echo "Selected profile doesn't exitst"
        echo "Please try again"
    fi
else
    echo "No servers specified"
    echo "Please try again"
fi
